services:
  sem:
    image: sem
    # build: .
    container_name: sem
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      ADMINS: ${ADMINS}
      ALLOWED_SERVERS: ${ALLOWED_SERVERS}