services:
  sem:
    image: yashubeast/nerv:sem
    container_name: sem
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      ADMINS: ${ADMINS}
      ALLOWED_SERVERS: ${ALLOWED_SERVERS}