services:
  sem:
    image: semi
    build: .
    container_name: sem
    volumes:
      - sql-data:/sem/assets
    environment:
      - TOKEN_FILE=/run/secrets/token
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

secrets:
  token:
    external: true

volumes:
  sql-data: